erDiagram
    subjects {
        int id PK
        varchar name
        timestamp created_at
        timestamp updated_at
    }
    cache {
        varchar key
        int expiration
    }
    users {
        int id PK
        varchar nom
        varchar prenom
        varchar photo
        varchar adress
        enum gender
        enum role
        date birthday
        varchar birthplace
        int tel
        varchar email
        timestamp email_verified_at
        varchar password
        timestamp created_at
        timestamp updated_at
    }
    password_reset_tokens {
        varchar email
        varchar token
        timestamp created_at
    }
    jobs {
        int id PK
        varchar queue
    }
    cache_locks {
        varchar key
        varchar owner
        int expiration
    }
    exams {
        int id PK
        varchar status
        date date
        timestamp created_at
        timestamp updated_at
    }
    job_batches {
        varchar id PK
        varchar name
        int total_jobs
        int pending_jobs
        int failed_jobs
        int cancelled_at
        int created_at
        int finished_at
    }
    school_classes {
        int id PK
        varchar name
        timestamp created_at
        timestamp updated_at
    }
    failed_jobs {
        int id PK
        varchar uuid
        text connection
        text queue
        timestamp failed_at
    }
    school_class_student {
        int id PK
        timestamp created_at
        timestamp updated_at
    }
    levels {
        int id PK
        varchar name
        timestamp created_at
        timestamp updated_at
    }
    directeur {
        int id PK
        timestamp created_at
        timestamp updated_at
    }
    teachers {
        int id PK
        timestamp created_at
        timestamp updated_at
    }
    students {
        int id PK
        varchar code
        timestamp created_at
        timestamp updated_at
    }
    sessions {
        varchar id PK
        varchar ip_address
        text user_agent
        int last_activity
    }

    subjects ||--o{ teachers : "subject_id"
